template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true
minus_negate: false

rules:
  - labels: ['C: infrastructure']
    patterns: ['*|!@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '@(requirements|.github)/**']

  - labels: ['C: source']
    patterns: ['**/@(*.py|*.sublime-@(keymap|menu|settings|commands))|!tests']

  - labels: ['C: docs']
    patterns: ['**/*.md|docs/**']

  - labels: ['C: tests']
    patterns: ['tests/**']

  - labels: ['C: settings']
    patterns: ['*.sublime-@(keymap|menu|settings|commands)']

  - labels: ['C: windows']
    patterns: ['lib/notify/*_windows.py']

  - labels: ['C: macos']
    patterns: ['lib/notify/*_@(osx|macos).py']

  - labels: ['C: linux']
    patterns: ['lib/notify/*_linux.py']

# Label management

labels:
- name: 'C: macos'
  color: subcategory
  description: Related to macOS notifications.

- name: 'C: windows'
  color: subcategory
  description: Related to the Windows notifications.

- name: 'C: linux'
  color: subcategory
  description: Related to the Linux notifications.
